# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MParticleSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MParticleSample
  pod 'mParticle-Apple-SDK', '~> 6.12.3'

  target 'MParticleSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
